### ISSUE TITLE
Isn't "oznámení" a better term than "výzva" for the Czech interface?

### ISSUE THREAD

**Issue by svatek** [opendatacz/pc-filing-app#33]
Although in general language "výzva" is an adequate equivalent of "call", I would say that the specific technical term for "Call for tenders" is "Oznámení o zakázce". Please, check it and possibly fix.

**Comment by jakhrkal** [comment]
According to 
http://europa.eu/youreurope/business/public-tenders/tools-database/index_en.htm - http://europa.eu/youreurope/business/public-tenders/rules-procedures/index_cs.htm  
and 
http://www.portal-vz.cz/getmedia/512a7c3b-bfd6-4396-af46-5c0e518777a7/Smernice_18_2004_UK - http://www.portal-vz.cz/getmedia/c56beeff-3fb9-4adb-85f3-1ee3fe888e63/smernice-18-cs (in Article 29), 
I believe "Výzva k podání nabídek" is the the best term for "Call for tenders". However, other term can be used if required. Otherwise, please close this issue.

**Comment by svatek** [comment]
OK, I trust your review, let's keep it.
