### ISSUE TITLE
Supplier's account is not displayed

### ISSUE THREAD

**Issue by svatek** [opendatacz/pc-filing-app#54]
When clicking on "My account" from the supplier menu, only the progress bar appears.
In FF: the call to "http://lod2.vse.cz:8080/pc-filing-app/js/cpv-codes-en_US.js" produces "HTTP/1.1 404 Not Found"
In Chrome: the message is "Uncaught ReferenceError: cpvCollection is not defined (anonymous function)"

**Comment by jindrichmynarz** [comment]
Note: this issue was closed by 89d18d312c04846aa844e5a02722b87456ad225f. The cause of the issue was that some browsers encode language locale with language sub-tag, e.g., "en_US" instead of plain "en". This was fixed by using JSP's `pageContext.request.locale.language` instead of `pageContext.request.locale`.
